@startuml

!include <C4/C4_Context>

LAYOUT_WITH_LEGEND()

title Диаграмма контекста (C1) — Цифровая платформа «АгроПром X»

' Пользователи
Person(director, "Директор хозяйства", "• Управление предприятием\n• Принятие стратегических решений")
Person(analyst, "Аналитики [...]", "• Анализ эффективности бизнеса\n• Подготовка отчетности")
Person(agronom, "Агрономы [...]", "• Контроль полевых работ\n• Мониторинг состояния культур")
Person(mechanic, "Механики [...]", "• Мониторинг состояния техники\n• Контроль техобслуживания")
Person(operator, "Операторы теплиц [...]", "• Управление микроклиматом\n• Контроль полива и освещения")

' Внутренний контур предприятия
Enterprise_Boundary(company, "Цифровая экосистема «АгроПром X»") {
System_Boundary(agro, "Тепличные комплексы [...]"){
System(edge,"Edge-контур","• Датчики почвы\n• Тепличные датчики\n• Камеры\n• Метеостанции\n• Системы автополива")
    System(fields_sys, "Система мониторинга полей", "• Сбор телеметрии с датчиков\n• Трекинг сельхозтехники\n• Данные метеостанций")
    System(greenhouse_sys, "Система управления теплицами", "• Локальная автоматизация\n• Контроллеры оборудования\n• SCADA-интерфейсы")
    }
    System(agroprom, "Ядро платформы «АгроПром X»", "• Центральное хранилище данных\n• Аналитические модули\n• BI-визуализация\n• Интерфейс(Web, mobile)")
}

' Внешние системы
System_Ext(erp, "ERP-система (1С:Агро)", "• Финансовый учет\n• Складской учет\n• Кадровый учет")

' Связи пользователей с системами
Rel(director, agroprom, "Управляет хозяйством и получает рекомендации", "Web")
Rel(analyst, agroprom, "Анализируют отчеты и графики", "BI")
Rel(agronom, agroprom, "Контролируют состояние полей", "Mobile")
Rel(mechanic, fields_sys, "Мониторят/корректируют параметры техники", "IoT")
Rel(operator, greenhouse_sys, "Управляют климатом и поливом", "SCADA")

' Взаимодействие между внутренними системами
Rel(edge,fields_sys,  "Передает данные", "Network")
Rel(edge,greenhouse_sys,  "Получает команды", "Network")
Rel(fields_sys, agroprom, "Передает телеметрию и сырые данные", "IoT протоколы")
Rel(greenhouse_sys, agroprom, "Синхронизирует события и агрегированные данные", "API")

' Связь с внешней системой
Rel(agroprom, erp, "Синхронизирует данные", "REST API")

@enduml
