@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title Диаграмма контекста (C1) — Цифровая платформа «АгроПром X»

' Пользователи
Person(director, "Директор хозяйства", "• Управление предприятием\n• Принятие стратегических решений")
Person(analyst, "Аналитики [...]", "• Анализ эффективности бизнеса\n• Подготовка отчетности")
Person(agronom, "Агрономы [...]", "• Контроль полевых работ\n• Мониторинг состояния культур")
Person(mechanic, "Механики [...]", "• Мониторинг состояния техники\n• Контроль техобслуживания")
Person(operator, "Операторы теплиц [...]", "• Управление микроклиматом\n• Контроль полива и освещения")
Person(farmer, "Фермеры [...]", "• Управление кормушками, поилками\n• Контроль состояния поголовья")


' Внутренний контур предприятия
Enterprise_Boundary(company, "Цифровая экосистема «АгроПром X»") {
    System(fields_sys, "Система мониторинга полей", "• Сбор телеметрии с датчиков\n• Трекинг сельхозтехники\n• Данные метеостанций")
    System(greenhouse_sys, "Система управления теплицами", "• Локальная автоматизация\n• Контроллеры оборудования\n• SCADA-интерфейсы")
    System(agroprom, "Ядро платформы «АгроПром X»", "• Центральное хранилище данных\n• Аналитические модули\n• BI-визуализация\n• Интерфейс(Web, mobile)")
    System(farm_sys, "Система мониторинга ферм", "• Сбор данных с кормушек и поилок\n• Сбор и анализ данных видеонаблюдения за животными")
    System(food_sys, "Система управления фермой", "• Локальная автоматизация\n• Контроллеры кормушек/поилок/освещения")
}

' Внешние системы
System_Ext(erp, "ERP-система (1С:Агро)", "• Финансовый учет\n• Складской учет\n• Кадровый учет")
System_Ext(AI_model, "ИИ-модель трекинга животных", "• Анализ данных видеонаблюдения\n• Прогнозирование питания и ухода")

' Связи пользователей с системами
Rel(director, agroprom, "Управляет хозяйством и получает рекомендации", "Web")
Rel(analyst, agroprom, "Анализируют отчеты и графики", "BI")
Rel(agronom, agroprom, "Контролируют состояние полей", "Mobile")
Rel(mechanic, fields_sys, "Мониторят/корректируют параметры техники", "IoT")
Rel(operator, greenhouse_sys, "Управляют климатом и поливом", "SCADA")
Rel(farmer, food_sys, "Управляют кормушками/поилками на основании данных мониторинга", "SCADA")
Rel(farmer, agroprom, "Контролируют состояние ферм", "Mobile")

' Взаимодействие между внутренними системами
Rel(fields_sys, agroprom, "Передает телеметрию и сырые данные", "IoT протоколы")
Rel(greenhouse_sys, agroprom, "Синхронизирует события и агрегированные данные", "API")
Rel(farm_sys, agroprom, "Передает сырые данные и видеоданные", "IoT протоколы, gRPC")
Rel(food_sys, agroprom, "Получает результаты мониторинга, синхронизирует данные и события", "API")

' Связь с внешней системой
Rel(agroprom, erp, "Синхронизирует данные", "REST API")
Rel(agroprom, AI_model, "Передает видеоданные, получает результаты анализа", "gRPC")

@enduml
